name: amasyaappdriver
description: Amasya App Driver
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  auto_route: ^5.0.4
  avatar_glow: ^2.0.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.8.2
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.9
  custom_radio_grouped_button: ^2.1.2+2
  dartz: ^0.10.1
  day_night_switcher: ^0.2.0+1
  device_info_plus: ^8.1.0
  dio: ^5.1.1
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  file_picker: ^5.2.6
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  firebase_storage: ^11.2.4
  floating_action_bubble: ^1.1.4
  flutter:
    sdk: flutter
  flutter_adaptive_ui: ^0.8.0+1
  flutter_bloc: ^8.1.2
  flutter_cached_pdfview: ^0.4.1
  flutter_conditional_rendering: ^2.0.0
  flutter_datetime_picker: ^1.5.1
  flutter_html: ^3.0.0-beta.2
  flutter_image_compress: ^1.0.0
  flutter_image_map: ^0.9.3
  flutter_polyline_points: ^1.0.0
  flutter_secure_storage: ^8.0.0
  flutter_staggered_grid_view: ^0.6.2
  fluttertoast: ^8.2.2
  form_field_validator: ^1.1.0
  full_screen_image: ^2.0.0
  get_it: ^7.2.0
  google_maps_flutter: ^2.3.1
  group_button: ^5.2.2
  hive: ^2.2.3
  http: ^0.13.6
  image_picker: ^0.8.7
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  location: ^4.4.0
  mask_text_input_formatter: ^2.4.0
  multiple_result: ^4.0.0
  path_provider: ^2.0.13
  permission_handler: ^10.4.0
  shared_preferences: ^2.2.0
  signature: ^5.3.2
  slide_countdown: ^0.5.0
  url_launcher:
  url_strategy: ^0.2.0
  webview_flutter: 4.2.0
  webview_flutter_platform_interface: ^2.3.1
dependency_overrides:
  webview_flutter_wkwebview: '3.5.0'
dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_flavorizr: ^2.1.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  image_path: "assets/images/amasya_launcher_icon.png"
  adaptive_icon_background: "#235586"
  adaptive_icon_foreground: "assets/images/amasya_launcher_icon.png"
  ios: true
  remove_alpha_ios: true
  android: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
  injectable_generator: ^2.1.4

  json_serializable: ^6.6.1
  lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
