/// STORAGE KEYS
const String authTokenKey = "authToken";
const String refreshTokenKey = "refreshToken";
const String themeMode = "themeMode";

class ConstantString {
  String aynaliMagara =
      "Şehir merkezine 3,3 km uzaklıktadır. Kaya mezarlarının en iyi işlenmiş ve tamamlanmış olanıdır. Yerden dört basamakla çıkılan mezar düz bir kayaya oyulmuştur. Genişliği 9,8 metre yüksekliği 13 metre'dir. Mağaranın dış cephe yüzeyi perdahlanarak parlatılmıştır. Buraya Aynalı Mağara denmesinin nedeni de, güneş vurduğu zaman mağaranın cephesinin parlamasıdır. M.Ö. 2. yy da Helenistik çağda Amasya’da yaşamış Mitra Rahibi TES’in anıtsal mezarıdır. Mağaranın içinin çok geniş olması ve duvarlarda yer alan renkli resimler ve alınlığında yazan “Büyük Rahip Tes” yazısı bu düşünceyi destekler. Hz. İsa’nın on iki havarisinden birinin, Hristiyanlığı bu mağarada yaydığı da rivayet edilir.";
  String amasyaKalesi =
      "Harşane Dağı adlı dik kayalıklar üzerindedir. Harşena Kalesi adıyla da bilinir. Denizden 700, Yeşilırmak'tan ise 300 metre yüksekte bulunmaktadır. azı tarihçilere göre kaleyi Pontus Kralı Mithridates yaptırmıştır. Bazılarına göre ise Kumandan Karsan veya Harsana yaptırdığı için kale Harşana / Harşena ismini almıştır. Kalenin Belkıs, Saray, Maydonos ve Meydan adlarına dört kapısı, kalede Cilanbolu adı verilen ve kalenin orta yerinde yüksekçe bir yerden kayaya oyulmuş 150 basamakla aşağıya inilen 8 metre çapında bir dehliz, sarnıç, zindan bulunmaktadır. Kaleden 70 metre aşağıda Yeşilırmağa ve kral mezarlarına kadar uzanan M.Ö. III. yüzyıla ait merdivenli yer altı yolu, burç ve cami kalıntıları vardır.";
  String alcakKopri =
      "Roma döneminde, zamanın kent merkezi durumundaki kale ve çevresini Yeşilırmak'ın karşı kıyısına bağlamak üzere inşa edilmiştir. Düzgün kesme taşlarla dört yüksek kemer oluşturacak şekilde inşa edilen köprünün bu yüksek ayakları zaman içinde Yeşilırmak'ın yükselen yatağına gömülmüş, kemerlerin sadece üst kısımları görünür kalmıştır. Kemerlerin üzerindeki köprü tablası da su yüzeyine yaklaştığından halk bu zamandan sonra köprüyü “Alçak Köprü” olarak adlandırmıştır. Dönemin Amasya Valisi Ziya Paşa tarafından 1865'te köprü kemerleri üzerine ayaklar inşaa edilerek günümüze kadar gelmiştir.";
  String amasyaSaatKulesi =
      "Nergis Köprüsü üzerinde 1865 yılında Ziya Paşa tarafından yaptırılmıştır. Bu tarih saat kulesinin ilk yapılış tarihidir. Kaidesi dörtgen prizma şeklinde ve mermerden yapılmış, gövdesi silindirik bir görünümüne sahip ve tuğladan yapılmış olan Amasya saat kulesinin üst bölümü ahşap dörtgen prizma şeklindedir. Yapımından 75 yıl sonra önemli bir deprem yaşayan Amasya saat kulesi bu depreme rağmen ayakta kalabilmiştir. Ancak 1940 yılında Hükümet Köprüsü'nün yapımına engel olduğu gerekçesiyle yıkılmıştır. Saat kulesi 2002 yılında yeniden inşa edilmiştir.";
  String halifetGaziTurbesi =
      "Türbenin genel olarak yapım tarihinin 1225 yılı olduğu söylense de türbenin batı duvarında taş kalıntılarının kaldığı medreseyle aynı tarihte ya da daha önce yapılmış olması gerektiği ileri sürülmektedir. Kitabesinden medresenin 1210 yılında yapıldığı anlaşılmaktadır. Türbenin de bu tarihte veya daha önce yapıldığı ve Danişmend emirlerinden Halifet Gazi tarafından yaptırıldığı kabul edilir.Son yıllarda onarılan türbe, kesme taştan kare plan üzerine sekizgen cepheli kule şeklinde yapılmıştır.";
  String borabayGolu =
      "Doğa yürüyüşü, piknik ve kamp için son derece uygudur. Denizden 800 metre yükseklikteki göl küçük bir akarsuyun etraftan gelen yıkıntılarla tıkanması sonucu oluşmuş, doğal bir set gölüdür. İl merkezine 65 km ve Taşova ilçesine 15 km mesafede olan göl, 80 metre genişlik ve 25 metre derinliğe sahiptir. Doğu batı yönünde uzanan bir vadi de yer alır. 900 x 300 metre ölçülerindeki gölün etrafında kayın, sarıçam, sedir, kestane ağaçları yer alır. Gölün rengi zümrüt yeşilidir.";
  String amasyaArkeolojiMuzesi =
      "Geç Neolitik Erken Kalkolitik Çağ'dan itibaren Tunç Çağı, Hitit, Urartu, Frig, İskit, Pers, Helenistik, Roma, Bizans, Selçuklu ve Osmanlı Dönemlerine ait 13 ayrı medeniyetin eserlerini bir arada görebileceğiniz müze 1925’te kurulmuştur. 1977 yılında bugünkü bina yapılmış ve 1980 yılında Amasya Arkeoloji Müzesi hizmete açılmıştır. Müze binasının batısında bulunan müze bahçesi içerisinde Hitit, Helenistik, Roma, Bizans, İlhanlı, Selçuklu ve Osmanlı Dönemlerine ait taş eserler sergilenmektedir. Daha Önce Müzenin bahçesinde bulunan ve Selçuklu Sultanı I. Mesud'a ait olan türbe içinde sergilenen İlhanlılar dönemine ait 14. yy.'dan kalma mumyalar Müze içerisindeki özel bir bölümde sergilenmektedir. Onüç farklı medeniyete ait arkeolojik ve etnografik eserlerin sayısı 24 bini bulmuştur.";
  String amasyaTarihi =
      "Yeşilırmak vadisi Harşena Dağı eteklerine kurulan Amasya, 7 bin yılın üzerindeki eski tarihi boyunca bilim adamları, sanatkarlar, şairler yetiştirmiş, Osmanlı şehzadelerinin eğitim gördüğü, Dünyanın en güzel Misket elması, kirazı, şeftalisi ve bamyasının üretildiği, gezip görülecek pek çok tarihi ve doğal güzelliği bulunan ilginç bir şehirdir.\n Milli Mücadelenin temellerinin atıldığı Kurtuluş savaşının ilk önemli adımını teşkil eden Amasya Genelge’sinin 22 Haziran 1919’da okunduğu kent, krallık başkentliği yapmış tarihi ve doğal güzellikleriyle önemli şehirlerimizden biridir.";
 String ferhatSirin = " Müzemiz Amasya-Tokat karayolu üzerinde bulunmaktadır. Yapımı 2013 yılında tamamlanmış olup 14 Şubat 2014 yılında hizmete açılmıştır. Dünyada ve Türkiye de ilk ve tek bütün âşıkları içerisinde bulunduran müzedir.60 metre boyunda 7 metre genişliğinde kurulmuş tematik müzedir. 8 odası ve 8 ayrı hikâyesi ile her odaya ait farklı fon müzikleriyle sizleri Beşer-i Aşktan İlah-i Aşk’a yolculuk yaptıracak bir müzedir. 1. ODA: FERHAT İLE ŞİRİN EFSANESİ Ferhat dönemin önemli nakkaşıdır. Mehmene Banu Sultan, kız kardeşi Şirin için yaptırdığı köşkün süsleme işini Ferhat’a verir. Ferhat köşkte çalışırken Şirin’i görür ve birbirilerine sevdalanırlar. Ferhat Şirin’i Sultandan ister. Sultan kız kardeşini Ferhat’a vermek istemez. Bir şart öne sürer, Ferhat’ı oyalamak için Elma Dağını delip şehre su getirmesini ister. Ferhat Şirin’e olan sevdasını verdiği aşkla kabul eder ve başlar işe koyulmaya. Haberi alan Amasya halkı Ferhat’ın yanına gider ve bu aşktan vazgeçmesini, bu şartı yerine getiremeyeceğini söylerler. Ferhat o esnada elindeki külüngü dağa vurduğu anda ufacık kaya parçası dağılır etrafa. Aşkından aldığı güçle etraftakilere derki: ‘ Gördünüz mü? Çoğu bitti azı kaldı.’ Mehmene Banu Sultan bir duyar ki Ferhat şehre suyu getirmek üzere… Hemen dadısıyla başka bir plan yaparlar. Evde un helvası kavurup tabağa koyarlar ve dadısıyla Ferhat’a gönderir. Dadısı Ferhat’ın yanına giderek Şirin’in öldüğünü ve helvasını getirdiğini söyler. Ferhat duyduğu sözler karşısında kendisinden geçer ve külüngü havaya fırlatır. Külünk Ferhat’ın başına düşer ve oracıkta hayatını kaybeder. Amacına kavuşan dadı koşarak Şirin’e gider ve Ferhat’ın öldüğünü söyler. Bu haberi duyan Şirin Ferhat’ın yanına gider ve Ferhat’ın öldüğünü görünce o acıya dayanamaz ve kayalıklardan kendini atarak can verir. Her iki sevgiliyi can verdikleri kayalıklarda yan yana gömerler. Derler ki; her bahar mevsimi iki mezar üzerinde biri beyaz biri kırmızı iki gül açarmış. Bu iki gül tam birbirlerine kavuşmak üzereyken mezarlarının ortasından karaçalı çıkar ve mezarlarında bile kavuşmalarını engellermiş.";

}
